export enum EStatusShipping {
  CANCELED = 'CANCELED',
  UNVERIFIED = 'UNVERIFIED',
  VERIFIED = 'VERIFIED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
}
export enum Status {
  INACTIVE,
  ACTIVE,
}
